### PR TITLE
Head links and url untracking

### PR DESCRIPTION
**Pull request by mmmmmrob**

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
looking great, let me review this a bit more before I merge!

**Comment by mmmmmrob** [comment]
Does this look OK? Happy to take suggestions :)

**Comment by jaimeiniesta** [comment]
It does indeed, it's just that I'm very busy this week. Will release it this weekend I guess :)

**Comment by jaimeiniesta** [comment]
Merged!

I'm waiting for https://github.com/jaimeiniesta/metainspector/pull/133 to be merged to release 4.5

**Comment by jaimeiniesta** [comment]
@mmmmmrob before we release 4.5, I think we should consider absolutifying and unrelativizing the URLS returned on `head_links`, just as we do currently on the Links parser.

Related: https://github.com/jaimeiniesta/metainspector/issues/135

What do you think?

**Comment by jaimeiniesta** [comment]
@jschwindt has gone ahead and added absolutifying and unrelativizing to the head links.

Released on 4.5! Thanks!

https://github.com/jaimeiniesta/metainspector/blob/master/CHANGELOG.md

**Pull request merged**
