### PR TITLE
Remove <script> tag from text nodes

### PR DESCRIPTION
**Pull request by mib32**
Possible solution for #170

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
Thanks for the PR!

I like this as a start, but how about making it strip not only the <script> tag, but, potentially, all tags using an HTML sanitizer with a good default?

Also, remember to add specs for that :+1:

**Comment by jaimeiniesta** [comment]
@mib32 Sorry, not sure if you read my previous comment; I just noticed that Github removed all content after I typed that "script" tag. Now it reads complete.

**Comment by mib32** [comment]
@jaimeiniesta About stripping all tags, I was thinking that we wouldn't want to lose `span`s and `i`s and stuff like that, what do you think?

**Comment by mib32** [comment]
Because it can contain some essential data

**Comment by jaimeiniesta** [comment]
Yeah, I think that the idea is stripping the tags, but not its content in that case. Like:

```html
A <i>good</i> title with <span>something</span>.<script>alert('booh');</script>
```

becomes:

```
A good title with something.
```

Not sure how to do this and how to make this configurable, but we could take a look at [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer) to get an idea, and if we like that, probably use [loofah](https://github.com/flavorjones/loofah) which is what rails uses internally.

**Comment by jaimeiniesta** [comment]
Probably it will be best to not make this too configurable, and just let you decide if you want the raw content, or strip all tags (keeping the safe content) as in the previous example. But let's see what options we have.

**Comment by mib32** [comment]
@jaimeiniesta OK, thanks, i'll catch up on that.

**Comment by mib32** [comment]
@jaimeiniesta The loofah suites perfectly indeed, i propose to use it, i love that it's used by rails also. I looked through rails_html_sanitizer code and basically repeated the way they used, only we don't use custom scrubber, in favour of built-in one. This sadly strips unknown tags, and if you think it is bad, than we'll simply to write custom scrubber. 

Including loofah in gemspec breaks the tests, in the manner that Document hash now has `"http-equiv"=>{"content-type"=>["text/html; charset=utf-8"]}` instead of `"http-equiv"=>{}`.
Is it important or can i just adjust the test?

**Comment by jaimeiniesta** [comment]
Thanks @mib32, I need to find some time to review this, will come back to it.

**Comment by jaimeiniesta** [comment]
@mib32 sorry for taking so long to come back to this.

I think that adjusting the tests  to Loofah, regarding your previous comment, is fine.

Can you please rebase with master to resolve the conflicts so I can review it all?

Thanks!

**Comment by mib32** [comment]
@jaimeiniesta Done!

Anyway, how do you think, is that PR is worth merging, or just fuck them new 58 LoC?

**Comment by jaimeiniesta** [comment]
Thanks!

I totally this PR is worth merging and, in fact, I think we should use this not only on the title but also on the meta tags, description, etc., that is, `TextsParser` and `MetaTagsParser`.

**Comment by jaimeiniesta** [comment]
What I mean is that this PR only deals with the sanitization of `best_title` but we should do the same with `title` and `description` (through the `secondary_description` or through `meta[:description]`, which leads us to do the sanitization on anything that comes from `MetaTagsParser`).

**Comment by straight-shoota** [comment]
I don't like putting this as a flag in the configuration. Maybe you'll need for example sanitized values for title and raw for description or both raw and sanitized for some value.

Therefor I'd prefer accessors for raw and sanitized values and put the decision, which one to use to the place where the value is requested.
That should be as simple as this:
```
def title_raw
   # current implementation
end
def title
   Loofah.xml_fragment(title_raw).scrub!(:prune)
end
```
Add in some metaprogramming like `sanitized_attribute :title` and there would just need to be a `title_raw` method and the sanitized value is generated automatically. Easy to scale to every place where sanitation might be required.
If this idea seems worthwhile, I'll be happy to create a PR.

**Comment by jaimeiniesta** [comment]
@straight-shoota it sounds perfect to me, this way we can make every text sanitized by default and still provide a way to access the raw version of it.

Go ahead with the PR!

**Comment by jaimeiniesta** [comment]
Closing this PR in favor of https://github.com/jaimeiniesta/metainspector/pull/193

**Pull request closed without merging**
