### PR TITLE
Add spec for Faraday::SSLError rescue

### PR DESCRIPTION
**Pull request by dentarg**
Related to #149 and fda1ba663fb5ac8f2abe7cd8d8526f38ca3d05b0.

### CODE REVIEW

**Comment by dentarg** [comment]
> I see this is a non existent domain, would you change it to something like https://example.com instead?

Do you mean example.com or a real host (with HTTPS)? Because example.com resolves to 127.0.0.1, so not sure how big difference that makes :)

**Comment by jaimeiniesta** [comment]
I mean using the example.com - [that's what is for](https://en.wikipedia.org/wiki/Example.com) :)

Take a look at [how we fake the domains](https://github.com/jaimeiniesta/metainspector/blob/master/spec/spec_helper.rb#L25-L54), as we're faking the responses it does not matter what the real domain resolves to.

**Comment by dentarg** [comment]
Right, I get it. 

But we are not faking the request here, it's a real request, isn't it? https://github.com/dentarg/metainspector/blob/29c979e2db28e881dc13eb7bd09fb76918b99d4c/spec/request_spec.rb#L53-L55

I just did like "should handle socket errors" :)

**Comment by jaimeiniesta** [comment]
Well, it's not a fake request like the others, but we're faking it up in a certain way, to raise the exact exception we want.

The thing here is that we can use shorter, more readable domains, for the specs.

**Comment by dentarg** [comment]
@jaimeiniesta done

**Comment by jaimeiniesta** [comment]
Thanks!

**Pull request merged**
