### PR TITLE
Fix #166 by skipping non http(s) images

### LINKED ISSUE #166: base64 support
If you'll try to open specific page that has base64 image in it:

``` ruby
require 'metainspector'
i = MetaInspector.new('http://www.amazon.com/gp/product/B0107H5FJ6/ref=s9_simh_gw_g107_i3_r?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=desktop-1&pf_rd_r=1DSA92Q4PADKNTZBWAZY&pf_rd_t=36701&pf_rd_p=2079475242')
i.images.best
```

You will get an error:

```
Errno::ENAMETOOLONG: File name too long @ rb_sysopen - data:image/jpeg;base64,/9j/4AAQS...
```

This is because MetaInspector is not taking base64 images into consideration. Do you have any options or plans to support that? Do you think that it is needed feature?

### PR DESCRIPTION
**Pull request by jschwindt**
I created a fixture html to verify that issue #166 fails and after that I modified images.rb to skip any non HTTP url.

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
Will this work with images that have a relative URL (that is, not starting with `http`)?

**Comment by jschwindt** [comment]
Yes, because at that point image URLs are already "absolutified" (FastImage works only with absolute URLs). That said, we can wait to see if FastImage accepts my PR to support Data URIs (https://github.com/sdsykes/fastimage/pull/75) with the additional benefit of getting the width and height of the image.

**Comment by jaimeiniesta** [comment]
Cool! It's OK to wait then.

Can you check the failing Travis test please?

**Comment by jschwindt** [comment]
nokogiri-1.7.0 requires ruby version >= 2.1.0

[Official support for ruby 2.0 ended on 2016-02-24](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), maybe it's time to remove ruby 2.0 and add 2.4

**Comment by jaimeiniesta** [comment]
> Official support for ruby 2.0 ended on 2016-02-24, maybe it's time to remove ruby 2.0 and add 2.4

👍

**Comment by jaimeiniesta** [comment]
@jschwindt I've removed support for Ruby 2.0.0 and added support for Ruby 2.4.0 in master, please rebase so the checks pass on your PR.

Let's wait for the FastImage PR to be accepted anyway.

**Comment by jschwindt** [comment]
Done!

**Comment by jaimeiniesta** [comment]
@jschwindt now that your PR to FastImage has been merged, what's the next step regarding this PR? Shall we wait for a new FastImage gem release? Do you need to update anything here before we merge?

**Comment by jaimeiniesta** [comment]
@jschwindt they just released a new version of FastImage that includes your contribution, so I think there's no more need for this PR. Closing it, thanks!

**Comment by jschwindt** [comment]
You right, it shouldn't be necessary to check if the img src is http(s).

**Pull request closed without merging**
