### PR TITLE
Added option for forcing encoding before parsing

### PR DESCRIPTION
**Pull request by jnarowski**

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
Sorry for taking so long to review this. It looks good, do you think you can add some test?

**Comment by summera** [comment]
Be great if we could get this in soon 👍 . Currently monkey patching `MetaInspector::Request` to handle invalid encodings.

**Comment by jaimeiniesta** [comment]
I'm all 👍 to give a final review to this PR once it includes tests :)

**Comment by summera** [comment]
@jaimeiniesta opened PR https://github.com/jaimeiniesta/metainspector/pull/235 with spec. Right now it fails of course but should pass with what's in this PR. I would also suggest setting the encoding to `UTF-8` by default if no encoding option is passed in like so:

```ruby
@encoding           = options[:encoding] || "UTF-8"
```

**Comment by summera** [comment]
@jaimeiniesta checking back in here.

**Comment by jaimeiniesta** [comment]
Thanks @summera - do you think you could create a PR including the commits by @jnarowski and yours, so I can review it as a whole if the test passes?

**Comment by jaimeiniesta** [comment]
Thanks, let's continue on https://github.com/jaimeiniesta/metainspector/pull/239 please.

**Pull request closed without merging**
